from django.urls import path

from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('news/', views.news_list_view, name='news_list'),
    path('news/<int:news_id>/', views.news_detail_view, name='news_detail'),
    path('employees/', views.employees_list_view, name='employees_list'),
    path('employees/<int:employee_id>/', views.employee_detail_view, name='employee_detail'),
    path('documents/', views.documents_list_view, name='documents_list'),
    path('tickets/', views.tickets_list_view, name='tickets_list'),
    path('tickets/create/', views.ticket_create_view, name='ticket_create'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.profile_edit_view, name='profile_edit'),
    path('management/', views.management_dashboard_view, name='management_dashboard'),
    path('management/news/', views.management_news_list_view, name='management_news_list'),
    path('management/news/create/', views.management_news_create_view, name='management_news_create'),
    path('management/news/<int:news_id>/edit/', views.management_news_edit_view, name='management_news_edit'),
    path('management/news/<int:news_id>/delete/', views.management_news_delete_view, name='management_news_delete'),
    path('management/employees/', views.management_employees_list_view, name='management_employees_list'),
    path('management/employees/create/', views.management_employee_create_view, name='management_employee_create'),
    path('management/employees/<int:employee_id>/edit/', views.management_employee_edit_view, name='management_employee_edit'),
    path('management/employees/<int:employee_id>/delete/', views.management_employee_delete_view, name='management_employee_delete'),
    path('management/documents/', views.management_documents_list_view, name='management_documents_list'),
    path('management/documents/create/', views.management_document_create_view, name='management_document_create'),
    path('management/documents/<int:document_id>/edit/', views.management_document_edit_view, name='management_document_edit'),
    path('management/documents/<int:document_id>/delete/', views.management_document_delete_view, name='management_document_delete'),
    path('management/tickets/', views.management_tickets_list_view, name='management_tickets_list'),
    path('management/tickets/<int:ticket_id>/edit/', views.management_ticket_edit_view, name='management_ticket_edit'),
    path('management/departments/', views.management_departments_list_view, name='management_departments_list'),
    path('management/departments/create/', views.management_department_create_view, name='management_department_create'),
    path('management/departments/<int:department_id>/edit/', views.management_department_edit_view, name='management_department_edit'),
    path('management/departments/<int:department_id>/delete/', views.management_department_delete_view, name='management_department_delete'),
    path('management/services/', views.management_service_links_list_view, name='management_service_links_list'),
    path('management/services/create/', views.management_service_link_create_view, name='management_service_link_create'),
    path('management/services/<int:service_link_id>/edit/', views.management_service_link_edit_view, name='management_service_link_edit'),
    path('management/services/<int:service_link_id>/delete/', views.management_service_link_delete_view, name='management_service_link_delete'),
]
